version: "3.5"
services:
  protrip-loading:
    image: "protrip-loading:1"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8080"

    environment:
      ENV: prod
    restart: always
